### ISSUE TITLE
Config - where?

### ISSUE THREAD

**Issue by romanr** [yhayano-ponotech/ComfyUI-Fal-API-Flux#10]
"create config in root directory of project".  But there's no "project". where would that be?

**Comment by yhayano-ponotech** [comment]
@romanr 
It seems I may have caused some confusion. The config.ini file already exists in the root directory of this project, so please edit that one.

**Comment by romanr** [comment]
After adding that configuration,

I get this error at startup:

```
[rgthree-comfy] Loaded 42 fantastic nodes. 🎉

Traceback (most recent call last):
  File "/Users/r/ComfyUI/nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/roman/ComfyUI/custom_nodes/ComfyUI-Fal-API-Flux/__init__.py", line 1, in <module>
    from .modules.fal_api_flux_dev_node import FalAPIFluxDevNode
  File "/Users/r/ComfyUI/custom_nodes/ComfyUI-Fal-API-Flux/modules/fal_api_flux_dev_node.py", line 1, in <module>
    from .base_fal_api_flux_node import BaseFalAPIFluxNode
  File "/Users/r/ComfyUI/custom_nodes/ComfyUI-Fal-API-Flux/modules/base_fal_api_flux_node.py", line 2, in <module>
    import fal_client
ModuleNotFoundError: No module named 'fal_client'

Cannot import /Users/r/ComfyUI/custom_nodes/ComfyUI-Fal-API-Flux module for custom nodes: No module named 'fal_client'
Traceback (most recent call last):
  File "/Users/r/ComfyUI/nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/r/ComfyUI/custom_nodes/ComfyUI-fal-Connector/__init__.py", line 6, in <module>
    from .config import set_fal_credentials
  File "/Users/r/ComfyUI/custom_nodes/ComfyUI-fal-Connector/config.py", line 5, in <module>
    from fal_client.auth import MissingCredentialsError, FAL_RUN_HOST
ModuleNotFoundError: No module named 'fal_client'

Cannot import /Users/r/ComfyUI/custom_nodes/ComfyUI-fal-Connector module for custom nodes: No module named 'fal_client'
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
```

**Comment by romanr** [comment]
After I reinstalled the errors went away and I am back to what is was before,
 ![Google Chrome-MJ-1112 1831@2x](https://github.com/user-attachments/assets/93cecca7-0572-43d9-9e4a-a97f460341aa)
I get this after few seconds. and nothing in logs.

**Comment by yhayano-ponotech** [comment]
Is this error still happening? I will close this issue in 5 days.
