### ISSUE TITLE
Requirements error

### ISSUE THREAD

**Issue by romanr** [yhayano-ponotech/ComfyUI-Fal-API-Flux#5]
Am I doing something wrong?
My python 3.12 is too new?

`$ pip install -r requirements.txt`
```
Collecting numpy==1.24.3 (from -r requirements.txt (line 4))
  Using cached numpy-1.24.3.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/user/ComfyUI/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module
File "/private/var/folders/26/p_012vlj62bgnyfcn9qnkqfm0000gn/T/pip-build-env-fr70i2jg/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
```

**Comment by yhayano-ponotech** [comment]
@romanr 
I only tried this node on Python 3.11. I updated requirements.txt, so try again.
